# Generated by Django 5.1.6 on 2025-02-20 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Фото профиля')),
                ('address', models.TextField(blank=True, max_length=50, null=True, verbose_name='Адрес')),
                ('apartment_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Номер квартиры')),
                ('order_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер заказа')),
                ('login', models.CharField(blank=True, max_length=20, null=True, verbose_name='Логин')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержденный')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_denied', models.BooleanField(default=False, verbose_name='Отказ')),
                ('otp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Время создания OTP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
